<?php

namespace GeneralBundle\Repository;

/**
 * ProduitbouRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitbouRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBikeByName($nameBike){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM GeneralBundle:Produitbou p
                WHERE p.Nom LIKE :nameBike'
            )
            ->setParameter('nameBike', '%'.$nameBike.'%')
            ->getResult();
    }



    public function findProduitsEnReptureDeStock(){
        return $this->getEntityManager()->createQuery(
            'SELECT p 
                                  FROM GeneralBundle:Produitbou p
                                  WHERE p.QteTotal = 0')->getResult();
    }

    public function findBikeByStore($idStore){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM GeneralBundle:Produitbou p
                WHERE p.store_id LIKE :idStore'
            )
            ->setParameter('idStore', '%'.$idStore.'%')
            ->getResult();
    }

    public function findBikeByOwnerStore($idOwner)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                      FROM GeneralBundle:Produitbou p
                      WHERE p.idStore LIKE SELECT owner
                                            FROM GeneralBundle:Store s
                                            WHERE s.owner LIKE :idOwner'
            )
            ->setParameter('idOwner','%'.$idOwner.'%')
            ->getResult();
    }





}