<?php

namespace GeneralBundle\Repository;

/**
 * StoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $nameStore
     * @return mixed
     */
    public function findStoreByName($nameStore){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s.id
                FROM GeneralBundle:Store s
                WHERE s.nom LIKE :nameStore'
            )
            ->setParameter('nameStore', '%'.$nameStore.'%')
            ->getResult();
    }

    public function findStoreByOwner($idOwner){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s.id, s.nom, s.description
                FROM GeneralBundle:Store s, GeneralBundle:User u
                WHERE s.owner = u.id AND u.id LIKE :idOwner'
            )
            ->setParameter('idOwner', '%'.$idOwner.'%')
            ->getResult();
    }

    public function findStores(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s.id,s.nom,s.description,u.id, IDENTITY(s.owner)
                FROM GeneralBundle:Store s JOIN GeneralBundle:User u
                WHERE s.owner = u.id
                '
            )
            ->getResult();
    }

}
